spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/archive_center?characterEncoding=utf-8
    username: root
    password: 142857

server:
  port: 9999
